### ISSUE TITLE
Game fails to start under wayland session - Couldn't load a renderer

### ISSUE THREAD

**Issue by binaryfields** [flathub/net.unvanquished.Unvanquished#2]
The app terminates with the following message in the log:

```
--- Common Initialization Complete ---
Calling GetRefAPI…
SDL_Init( SDL_INIT_VIDEO )...
Using SDL Version 2.0.12
SDL_Init(SDL_INIT_VIDEO | SDL_INIT_NOPARACHUTE) FAILED (wayland not available)
Setting r_mode -2 failed, falling back on r_mode 3
SDL_Init( SDL_INIT_VIDEO )...
Using SDL Version 2.0.12
SDL_Init(SDL_INIT_VIDEO | SDL_INIT_NOPARACHUTE) FAILED (wayland not available)
Warn: Couldn't load a renderer
```

I needed to add the following overrides to make it work.

sudo flatpak override net.unvanquished.Unvanquished --socket=wayland && sudo flatpak override net.unvanquished.Unvanquished --env=SDL_VIDEODRIVER=wayland

**Comment by AsciiWolf** [comment]
Thanks for your report. Do you have XWayland working on your system?

**Comment by binaryfields** [comment]
Yes, I do have XWayland working.  I run other flatpaks that only run under X (IDEA IntelliJ/Android Studio/VS Code/etc).

O/S: Fedora 34
WM: Sway 1.6
XWayland 21.1.1

**Comment by AsciiWolf** [comment]
I was not able to reproduce your issue on my Fedora 34 system with GNOME Wayland session. The game launched fine using XWayland.

However, the game also seems to run fine directly on Wayland when using wayland socket. So, I think we could change https://github.com/flathub/net.unvanquished.Unvanquished/blob/master/net.unvanquished.Unvanquished.yml#L10 to:

```
  - --socket=wayland # Wayland access
  - --socket=fallback-x11 # Fallback X11 access
```

/cc @illwieckz

**Comment by necessarily-equal** [comment]
I don't think adding the wayland backend by default is a good idea as of now, as it is less test. See https://github.com/DaemonEngine/Daemon/issues/482.

@binaryfields can you give steps so one can reproduce the issue? or at least distro + distro version + desktop environment. For the record, I also have a wayland session and the flatpack works.
